---
title: "Day 4 - Exploring Data"
author: "Ruth Enriquez"
format: html
editor: visual
---

```{r}
#| warning: false
#| echo: false
library(tidyverse)
library(palmerpenguins)
library(GGally) # install.packages("GGally")
library(skimr) # install.packages("skimr")

#appear vs not appear, code chunk options, in R they go in the {r}, quarto its #| warning: false, use #| echo: false so code doesn't show up
```

Exploratory Data Viz

Check out your data a bit:

```{r}
#| include: false

# Tell me the column names
names(penguins)

# What are the dimensions
dim(penguins)

# Can you show me the first 6 lines?
head(penguins)

# Can you show me the last 6 lines?
tail(penguins)
```

in console view(penguins) to bring up data-set

```{r}
skim(penguins)
```

```{r}
#pairs plot, if you use :: you can see whats avaiable

#| include: false
GGally::ggpairs(penguins)
```

## Jitterplot

Flipper length by species

```{r}

#| fig.cap: "Figure Caption :)"
ggplot(data = penguins, aes(x = species, y = flipper_length_mm)) + 
  geom_jitter(width = 0.2,
              alpha = 0.5,
              aes(color = species)) + 
  geom_boxplot(fill = NA) +
  theme_light() +
  scale_color_manual(values = c("darkorchid4", "cyan4", "goldenrod")) +
  labs(x = "Penguin Species",
       y = "Flipper Species",
       title = "Palmer Archipelago Penguin Flippers")

#alpha is used for transparency
```

```{r}
ggplot(data = penguins, aes(x = bill_length_mm)) +
  geom_histogram(aes(fill = species), color ="magenta") +
  facet_wrap(~species, ncol = 1)
```


